### ISSUE TITLE
Receiving Error When Attempting to Complete the NodeJS Integration Steps

### ISSUE THREAD

**Issue by coreyphillips** [LNP-BP/rgb-node#30]
Is anyone else having this issue? After attempting to complete the NodeJS Integration steps running `npm i` throws the following error:

```
> nodejs@0.1.0 preinstall /Users/coreyphillips/Documents/testing/rgb-node/ffi/nodejs
> cargo build && swig -javascript -node -c++ swig.i

warning: Patch `torut v0.1.3 (https://github.com/afilini/torut?branch=vendored-openssl-android#41c2dcf0)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
warning: use of deprecated item 'std::vec::Vec::<T>::remove_item': Removing the first item equal to a needle is already easily possible with iterators and the current Vec methods. Furthermore, having a method for one particular case of removal (linear search, only the first item, no swap remove) but not for others is inconsistent. This method will be removed soon.
   --> src/contracts/fungible/data/asset.rs:171:21
    |
171 |         allocations.remove_item(&old_allocation).is_some()
    |                     ^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.30s

> nodejs@0.1.0 install /Users/coreyphillips/Documents/testing/rgb-node/ffi/nodejs
> node ./node_modules/node-gyp/bin/node-gyp.js rebuild

  CXX(target) Release/obj.target/rgb_node/swig_wrap.o
../swig_wrap.cxx:1524:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  obj->SetAccessor(SWIGV8_CURRENT_CONTEXT(), SWIGV8_SYMBOL_NEW(symbol), getter, setter);
  ^~~~~~~~~~~~~~~~
../swig_wrap.cxx:2112:37: warning: 'New' is deprecated [-Wdeprecated-declarations]
  resolver = v8::Promise::Resolver::New(args.GetIsolate());
                                    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4092:12: note: 'New' has been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2116:15: warning: 'Resolve' is deprecated [-Wdeprecated-declarations]
    resolver->Resolve(SWIG_NewPointerObj((new COpaqueStruct(static_cast< const COpaqueStruct& >((&result)->inner))), SWIGTYPE_p_COpaqueStruct, SWIG_POINTER_OWN |  0 ));
              ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4106:5: note: 'Resolve' has been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Resolve(Local<Value> value));
    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2119:15: warning: 'Reject' is deprecated [-Wdeprecated-declarations]
    resolver->Reject(v8::String::NewFromUtf8(args.GetIsolate(), (const char*) (&result)->inner.ptr));
              ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4110:5: note: 'Reject' has been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Reject(Local<Value> value));
    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2156:37: warning: 'New' is deprecated [-Wdeprecated-declarations]
  resolver = v8::Promise::Resolver::New(args.GetIsolate());
                                    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4092:12: note: 'New' has been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2160:15: warning: 'Resolve' is deprecated [-Wdeprecated-declarations]
    resolver->Resolve(SWIG_NewPointerObj((new COpaqueStruct(static_cast< const COpaqueStruct& >((&result)->inner))), SWIGTYPE_p_COpaqueStruct, SWIG_POINTER_OWN |  0 ));
              ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4106:5: note: 'Resolve' has been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Resolve(Local<Value> value));
    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2163:15: warning: 'Reject' is deprecated [-Wdeprecated-declarations]
    resolver->Reject(v8::String::NewFromUtf8(args.GetIsolate(), (const char*) (&result)->inner.ptr));
              ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4110:5: note: 'Reject' has been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Reject(Local<Value> value));
    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2207:37: warning: 'New' is deprecated [-Wdeprecated-declarations]
  resolver = v8::Promise::Resolver::New(args.GetIsolate());
                                    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4092:12: note: 'New' has been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2211:15: warning: 'Resolve' is deprecated [-Wdeprecated-declarations]
    resolver->Resolve(SWIG_NewPointerObj((new COpaqueStruct(static_cast< const COpaqueStruct& >((&result)->inner))), SWIGTYPE_p_COpaqueStruct, SWIG_POINTER_OWN |  0 ));
              ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4106:5: note: 'Resolve' has been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Resolve(Local<Value> value));
    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2214:15: warning: 'Reject' is deprecated [-Wdeprecated-declarations]
    resolver->Reject(v8::String::NewFromUtf8(args.GetIsolate(), (const char*) (&result)->inner.ptr));
              ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8.h:4110:5: note: 'Reject' has been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Reject(Local<Value> value));
    ^
/Users/coreyphillips/Library/Caches/node-gyp/10.15.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
10 warnings generated.
  SOLINK_MODULE(target) Release/rgb_node.node
clang: error: no such file or directory: '/Users/coreyphillips/Documents/testing/rgb-node/ffi/nodejs/../../target/debug/librgb.so'
make: *** [Release/rgb_node.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/coreyphillips/Documents/testing/rgb-node/ffi/nodejs/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/coreyphillips/.nmv/versions/node/v10.15.1/bin/node" "/Users/coreyphillips/Documents/testing/rgb-node/ffi/nodejs/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/coreyphillips/Documents/testing/rgb-node/ffi/nodejs
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs@0.1.0 install: `node ./node_modules/node-gyp/bin/node-gyp.js rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejs@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coreyphillips/.npm/_logs/2020-07-29T12_59_46_311Z-debug.log
```

**Comment by coreyphillips** [comment]
I only receive the above error when attempting to build from a Mac. Switching to a Linux machine seems to have resolved the problem.

**Comment by dr-orlovsky** [comment]
It might be related to node js version you are using on mac. Can you pls post details on it? (and NPM version as well)

**Comment by coreyphillips** [comment]
Sure thing:
```
node = v10.22.0
npm  = 6.14.6
```

**Comment by coreyphillips** [comment]
This is the error I receive when running `node ./node_modules/node-gyp/bin/node-gyp.js rebuild` from the terminal:

```

corey@MacBook-Pro nodejs % node ./node_modules/node-gyp/bin/node-gyp.js rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@10.22.0 | darwin | x64
gyp info find Python using Python version 3.8.5 found at "/usr/local/opt/python@3.8/bin/python3.8"
gyp info spawn /usr/local/opt/python@3.8/bin/python3.8
gyp info spawn args [ '/Users/corey/Documents/testing/rgb-node/ffi/nodejs/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/corey/Documents/testing/rgb-node/ffi/nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/corey/Documents/testing/rgb-node/ffi/nodejs/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/corey/Library/Caches/node-gyp/10.22.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/corey/Documents/testing/rgb-node/ffi/nodejs/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/corey/Library/Caches/node-gyp/10.22.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/corey/Documents/testing/rgb-node/ffi/nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/rgb_node/swig_wrap.o
../swig_wrap.cxx:1524:3: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
  obj->SetAccessor(SWIGV8_CURRENT_CONTEXT(), SWIGV8_SYMBOL_NEW(symbol), getter, setter);
  ^~~~~~~~~~~~~~~~
../swig_wrap.cxx:2112:37: warning: 'New' is deprecated [-Wdeprecated-declarations]
  resolver = v8::Promise::Resolver::New(args.GetIsolate());
                                    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4092:12: note: 'New' has
      been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2116:15: warning: 'Resolve' is deprecated [-Wdeprecated-declarations]
    resolver->Resolve(SWIG_NewPointerObj((new COpaqueStruct(static_cast< const COp...
              ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4106:5: note: 'Resolve' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Resolve(Local<Value> value));
    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2119:15: warning: 'Reject' is deprecated [-Wdeprecated-declarations]
    resolver->Reject(v8::String::NewFromUtf8(args.GetIsolate(), (const char*) (&re...
              ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4110:5: note: 'Reject' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Reject(Local<Value> value));
    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2156:37: warning: 'New' is deprecated [-Wdeprecated-declarations]
  resolver = v8::Promise::Resolver::New(args.GetIsolate());
                                    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4092:12: note: 'New' has
      been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2160:15: warning: 'Resolve' is deprecated [-Wdeprecated-declarations]
    resolver->Resolve(SWIG_NewPointerObj((new COpaqueStruct(static_cast< const COp...
              ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4106:5: note: 'Resolve' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Resolve(Local<Value> value));
    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2163:15: warning: 'Reject' is deprecated [-Wdeprecated-declarations]
    resolver->Reject(v8::String::NewFromUtf8(args.GetIsolate(), (const char*) (&re...
              ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4110:5: note: 'Reject' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Reject(Local<Value> value));
    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2207:37: warning: 'New' is deprecated [-Wdeprecated-declarations]
  resolver = v8::Promise::Resolver::New(args.GetIsolate());
                                    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4092:12: note: 'New' has
      been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2211:15: warning: 'Resolve' is deprecated [-Wdeprecated-declarations]
    resolver->Resolve(SWIG_NewPointerObj((new COpaqueStruct(static_cast< const COp...
              ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4106:5: note: 'Resolve' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Resolve(Local<Value> value));
    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../swig_wrap.cxx:2214:15: warning: 'Reject' is deprecated [-Wdeprecated-declarations]
    resolver->Reject(v8::String::NewFromUtf8(args.GetIsolate(), (const char*) (&re...
              ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8.h:4110:5: note: 'Reject' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use maybe version", void Reject(Local<Value> value));
    ^
/Users/corey/Library/Caches/node-gyp/10.22.0/include/node/v8config.h:327:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
10 warnings generated.
  SOLINK_MODULE(target) Release/rgb_node.node
clang: error: no such file or directory: '/Users/corey/Documents/testing/rgb-node/ffi/nodejs/../../target/debug/librgb.so'
make: *** [Release/rgb_node.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/corey/Documents/testing/rgb-node/ffi/nodejs/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/corey/.nvm/versions/node/v10.22.0/bin/node" "/Users/corey/Documents/testing/rgb-node/ffi/nodejs/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/corey/Documents/testing/rgb-node/ffi/nodejs
gyp ERR! node -v v10.22.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok 
```

**Comment by afilini** [comment]
Could you paste here the output of `ls -l /Users/coreyphillips/Documents/testing/rgb-node/ffi/nodejs/../../target/debug/`?

I think the issue here is that I hard-coded the path to the library to `librgb.so` which is the name it has on linux, but maybe on macos it's different (I'm expecting a `.dylib`).

**Comment by dr-orlovsky** [comment]
```console
% ls  -l ../../target/debug   
total 1276280
drwxr-xr-x   411 orlovsky  staff      13152 Jul 31 17:34 build
drwxr-xr-x  5192 orlovsky  staff     166144 Aug 13 11:06 deps
drwxr-xr-x     2 orlovsky  staff         64 May 26 13:50 examples
-rwxr-xr-x     2 orlovsky  staff   32130128 Jul 31 18:04 fungibled
-rw-r--r--     1 orlovsky  staff       3596 Jul 31 17:34 fungibled.d
lrwxr-xr-x     1 orlovsky  staff         19 Jul 31 17:34 fungibled.dSYM -> deps/fungibled.dSYM
drwxr-xr-x   185 orlovsky  staff       5920 Aug 13 11:06 incremental
-rw-r--r--     2 orlovsky  staff  145619664 May 26 17:31 libffi.a
-rw-r--r--     1 orlovsky  staff       3620 May 26 18:07 libffi.d
-rwxr-xr-x     2 orlovsky  staff    2687216 May 26 17:31 libffi.dylib
lrwxr-xr-x     1 orlovsky  staff         22 May 26 17:31 libffi.dylib.dSYM -> deps/libffi.dylib.dSYM
-rwxr-xr-x     2 orlovsky  staff   46578216 Jul 31 10:49 liblnpbp.dylib
lrwxr-xr-x     1 orlovsky  staff         41 Aug  6 16:15 liblnpbp.dylib.dSYM -> deps/liblnpbp-69b6db39da594be5.dylib.dSYM
-rw-r--r--     2 orlovsky  staff  271062152 Aug 13 11:06 librgb.a
-rw-r--r--     1 orlovsky  staff       3737 Aug 13 11:06 librgb.d
-rwxr-xr-x     2 orlovsky  staff   40344460 Aug 13 11:06 librgb.dylib
lrwxr-xr-x     1 orlovsky  staff         22 Jun 10 13:20 librgb.dylib.dSYM -> deps/librgb.dylib.dSYM
-rw-r--r--     2 orlovsky  staff   25843840 Jun 14 23:58 librgb.rlib
-rwxr-xr-x     2 orlovsky  staff   30636272 Jul 31 18:11 rgb-cli
-rw-r--r--     1 orlovsky  staff       3592 Jul 31 17:35 rgb-cli.d
lrwxr-xr-x     1 orlovsky  staff         17 Jul 31 17:35 rgb-cli.dSYM -> deps/rgb_cli.dSYM
-rwxr-xr-x     2 orlovsky  staff   27214800 Jun 15 15:49 rgbd
-rw-r--r--     1 orlovsky  staff       3391 Jun 15 15:38 rgbd.d
lrwxr-xr-x     1 orlovsky  staff         31 Jun 15 15:38 rgbd.dSYM -> deps/rgbd-55bb4bf6cfc5b6da.dSYM
-rwxr-xr-x     2 orlovsky  staff   31290120 Jul 31 18:04 stashd
-rw-r--r--     1 orlovsky  staff       3590 Jul 31 17:34 stashd.d
lrwxr-xr-x     1 orlovsky  staff         16 Jul 31 17:34 stashd.dSYM -> deps/stashd.dSYM
```
